"""Enterprise expansion

Revision ID: ff0bc0532ad1
Revises: 614ac5716b50
Create Date: 2026-07-02 11:35:29.970506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0bc0532ad1'
down_revision = '614ac5716b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('membership_tier', sa.String(length=32), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('capacity_sqft', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('performance_rating', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_id'), ['employee_id'], unique=True)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('break_start', sa.DateTime(), nullable=True),
    sa.Column('break_end', sa.DateTime(), nullable=True),
    sa.Column('working_hours', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('dest_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['dest_warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('qr_code', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('batch_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('warranty_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)
        batch_op.create_foreign_key('fk_products_warehouse_id', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_products_supplier_id', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_products_brand_id', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sales_customer_id', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_customer_id', type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_warehouse_id', type_='foreignkey')
        batch_op.drop_constraint('fk_products_supplier_id', type_='foreignkey')
        batch_op.drop_constraint('fk_products_brand_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.drop_column('unit')
        batch_op.drop_column('gst_rate')
        batch_op.drop_column('warranty_months')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('batch_number')
        batch_op.drop_column('qr_code')
        batch_op.drop_column('barcode')
        batch_op.drop_column('warehouse_id')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('brand_id')

    op.drop_table('stock_transfers')
    op.drop_table('purchase_orders')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_date'))

    op.drop_table('attendance')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employees_department'))

    op.drop_table('employees')
    op.drop_table('warehouses')
    op.drop_table('suppliers')
    op.drop_table('customers')
    op.drop_table('brands')
    # ### end Alembic commands ###
